---
title: "RWorksheet 4a"
author: "Andrey Sumadic"
date: "2023-10-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
1. 
#A. The vector "sHOE" has a column name   shoe_size and height
#   and you can see the inputted values.

sHOE <- data.frame(
  Shoe_size = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0),
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
)
sHOE
```

```{r}
#B.
Gender <- c("F", "F","F", "F", "M", "F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
SHOE <- cbind(sHOE, Gender)
SHOE
```

```{r}
#C.
mean(SHOE$Shoe_size)
mean(SHOE$Height)
```

```{r}
#D.Thereis a relation because you can determine the gender
#   based on their shoe size and height alone.
```

```{r}
2.
factor_months_vector <- factor(c("March","April","January","November","January","September","October","September","November","August","January","November","November","February","May","August","July","December","August","August","September","November","February","April"))
factor_months_vector
```

```{r}
3.
summary(factor_months_vector)
```

```{r}
4.
  factor_data <- c("East", "West", "North")
  Frequency <- c(1, 4, 3)

new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)
```

```{r}
5.
df <- read.table(file='/cloud/project/Worksheet#4/import_march.csv', header=TRUE, sep=',')
df
```

```{r}
6.
Input_Number <- readline(prompt = "Enter a number between 1-50: ")
if (Input_Number == 20 ){
  print("TRUE")
} else if (Input_Number < 1 && Input_Number > 50){
  print("The number selected is beyond the range of 1 to 50")
} else {
  paste(Input_Number)
}
```

```{r}
#7.
calculate_min_bills <- function(price_of_snack) {
  bill_denominations <- c(1000, 500, 200, 100, 50)
  total_bills <- 0
  
  for (bill in bill_denominations) {
    num_bills_needed <- price_of_snack %/% bill
    price_of_snack <- price_of_snack %% bill
    total_bills <- total_bills + num_bills_needed
  }
  
  cat("Minimum number of bills needed to purchase the snack:", total_bills, "\n")
}

price_of_snack <- 1350
calculate_min_bills(price_of_snack)
```

```{r}
8.
#a.
students <- data.frame(
  Name = c("Annie" , "Thea", "Steve", "Hanna"),
  Grade1 = c(85,65,75,95),
  Grade2 = c(65,75,55,75),
  Grade3 = c(85,90,80,100),
  Grade4 = c(100,90,85,90)
)
students

```

```{r}
#b.

students$Average <- (students$Grade1 + students$Grade2 + students$Grade3 + students$Grade4) / 4

for (i in 1:nrow(students)) {
  if (students$Average[i] > 90) {
    cat(students$Name[i], "'s average grade this semester is", students$Average[i], "\n")
  }
}
```

```{r}
#c
test1_average <- sum(students$Grade1) / nrow(students)
test2_average <- sum(students$Grade2) / nrow(students)
test3_average <- sum(students$Grade3) / nrow(students)
test4_average <- sum(students$Grade4) / nrow(students)

if (test1_average < 80) {
  cat("The 1st test was difficult.\n")
}
if (test2_average < 80) {
  cat("The 2nd test was difficult.\n")
}
if (test3_average < 80) {
  cat("The 3rd test was difficult.\n")
}
if (test4_average < 80) {
  cat("The 4th test was difficult.\n")
}

```

```{r}
#d.
for (i in 1:nrow(students)) {
  highest_grade <- students$Grade1[i]
  if (students$Grade2[i] > highest_grade) {
    highest_grade <- students$Grade2[i]
  }
  if (students$Grade3[i] > highest_grade) {
    highest_grade <- students$Grade3[i]
  }
  if (students$Grade4[i] > highest_grade) {
    highest_grade <- students$Grade4[i]
  }
  if (highest_grade > 90) {
    cat(students$Name[i], "'s highest grade this semester is", highest_grade, "\n")
  }
}
```

