---
title: "RWorksheet 4b"
author: "Andrey Sumadic"
date: "2023-11-08"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1.
vectorB <- c(1,2,3,4,5)

matrixB <- matrix(0, nrow = 5, ncol = 5) 
print(matrixB)
for(i in 1:5){
  for(j in 1:5){
    matrixB[i,j] <- abs(vectorB[i] - vectorB[j])
  }
}
print(matrixB)


```

```{r}
#2.
for(i in 1:5) {
  for(j in 1:i) {
    cat("*")
  }
  cat("\n")
}
```

```{r}
#3.
n <- as.integer(readline(prompt="Enter the number of terms: "))

a <- 0
b <- 1

print(b)

repeat {
  c <- a + b
  if (c > 500) {
    break
  }
  print(c)
  a <- b
  b <- c
}

```


```{r}
#4.
#a.
shoe <- read.csv("shoe data.csv")
shoes <- shoe[c(1:6),]
shoes

#b.
MaleSub<- subset(shoes, Gender == "Male")
FemSub<- subset(shoes, Gender =="Female")

print("Male Subset:")
print(MaleSub)

print("Female Subset:")
print(FemSub)

nrow(MaleSub)
nrow(FemSub)

#c
GraphMF<- table(shoes$Gender)
barplot(GraphMF,
        main = "Number of Males and Females",
        xlab = "Gender",
        ylab = "Count",
        col = c("red", "blue"),
        legend.text = c("Male", "Female"),
        beside = TRUE
)

legend("topright", legend = c("Male", "Female"), fill = c("red", "blue"))
```

```{r}
#5.
expenses <- c(60, 10, 5, 25)
labels <- c("Food", "Electricity", "Savings", "Miscellaneous")

pie(expenses, labels = labels, col = c("green","blue","yellow","red"), 
    main = "Monthly Expenses of Dela Cruz Family")

```

```{r}
#6.
#a.
data(iris)
str(iris)
```

```{r}
#b.
mean_iris <- c(mean(iris$Sepal.Length), 
               mean(iris$Sepal.Width),
               mean(iris$Petal.Length), 
               mean(iris$Petal.Width))

```

```{r}
#c.
species <- table(iris$Species)
pie(species, labels = names(species), col = c("blue","orange","green"), main = "Species Distribution in Iris Data")
```

```{r}
#d.
setosa <- iris[iris$Species=="setosa",]
versicolor <- iris[iris$Species=="versicolor",]  
virginica <- iris[iris$Species=="virginica",]

tail(setosa, n=6)
tail(versicolor, n=6)
tail(virginica, n=6)
```

```{r}
#e.
data(iris)

iris$Species <- as.factor(iris$Species)

plot(iris$Sepal.Length, iris$Sepal.Width,
     pch = as.integer(iris$Species),
     col = iris$Species,
     main = "Iris Dataset",
     sub = "Sepal width and length",
     xlab = "Sepal Length",
     ylab = "Sepal Width")

```

```{r}
#f.
#The scatterplot shows similarities between the sepal width and length. It ranges from 5.5 to 7.0. 
```

```{r}
#7.
library(readxl)
alexa_file <- read_excel("alexa_file.xlsx")
View(alexa_file)

#a.

```













