---
title: "RWorksheet#3b"
author: "Andrey Sumadic"
date: "2023-10-06"
output: pdf_document
---


```{r}
#a.
respondents <- 1:20

data <- data.frame(
  respondents,
  sex = c(2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2),
  fathers_occupation = c(1, 3, 3, 3, 1, 2, 3, 1, 1, 1, 3, 2, 1, 3, 3, 1, 3, 1, 2, 1), 
  persons_at_home = c(5, 7, 3, 8, 5, 9, 6, 7, 8, 4, 7, 5, 4, 7, 8, 8, 3, 11, 7, 6),
  siblings_at_school = c(6, 4, 4, 1, 2, 1, 5, 3, 1, 2, 3, 2, 5, 5, 2, 1, 2, 5, 3, 2),
  types_of_house = c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2)
)

data

#b
str(data)

#c.
mean(data$siblings_at_school)

#d.
data[1:2,]

#e.
data[c(3,5), c(2,4)]

#f.
types_houses <- data$types_of_house

#g.
data[data$sex == 1 & data$fathers_occupation == 1, ]

#h.
data[data$sex == 2 & data$siblings_at_school >= 5, ]

```

```{r}
3.
#a.
household <- read.csv("HouseholdData.csv", header = TRUE, sep = ",")
household

#b
household$Sex <- factor(household$Sex, 
                        levels = c("Male", "Female"),
                        labels = c(1,2))
household

#c.
household$Types.of.Houses <- factor(household$Types.of.Houses,  
                          levels = c("Wood", "Congrete", "Semi-congrete"),
                          labels = c(1,2,3))
household


#d.
household$Fathers.Occupation <- factor(household$Fathers.Occupation,  
                          levels = c(1,2,3),
                          labels = c("Farmer", "Driver", "Others")) 
household



#e.
household[household$Sex == 2 & household$Fathers.Occupation == "Driver",]

#f.
household[household$Siblings.at.School >= 5,]


```

```{r}
#4. This line graph shows that the number of tweets sent per day increased over the months represented,
#with less daily variability in later months compared to earlier ones. The visual representation 
#clearly conveys the trends in Twitter usage over time.
```
